# Google Cloud Build configuration for Rendertron
# Builds and deploys to Cloud Run automatically

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/rendertron:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/rendertron:latest'
      - '-f'
      - 'Dockerfile.rendertron'
      - '.'

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/rendertron:$SHORT_SHA'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'localpdf-rendertron'
      - '--image'
      - 'gcr.io/$PROJECT_ID/rendertron:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '60s'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'NODE_ENV=production,CACHE_MAX_AGE=3600,TIMEOUT=25000'

images:
  - 'gcr.io/$PROJECT_ID/rendertron:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/rendertron:latest'

timeout: '1200s'
