# Конфигурация codemcp для проекта LocalPDF
project_prompt = """
Ты работаешь над проектом LocalPDF - клиентский PDF инструмент на React/TypeScript.

🎯 КРИТИЧЕСКИ ВАЖНО - Первое действие в каждой сессии:
1. Проверь и создай структуру памяти в .claude/
2. Прочитай current-context.json для понимания текущего состояния
3. Выведи статус: "Где мы остановились"

📋 Принципы разработки:
- Privacy First: вся обработка в браузере
- Atomic Design System для компонентов
- TypeScript строгие типы (no any)
- Performance: Web Workers для файлов >10MB
- Error Handling: user-friendly + logging

🛠️ Технический стек:
- React 18 + TypeScript + Vite 4.5
- Tailwind CSS + Framer Motion
- pdf-lib + jsPDF + PDF.js
- Context API + Custom Hooks

⚠️ Критические правила:
- ВСЕГДА используй --legacy-peer-deps для npm
- НЕ обновляй vite и jsPDF без необходимости
- Структура коммитов: type(scope): description
- Проверки перед коммитом: type-check, lint, build, test

📁 Структура файлов памяти:
- .claude/project-state.json - главное состояние
- .claude/current-context.json - активный контекст
- .claude/session-log.md - детальный лог
- .claude/tech-decisions.md - технические решения
- .claude/known-issues.md - известные проблемы
- .claude/file-changes.md - изменения файлов

При каждом изменении обновляй соответствующие файлы памяти.
"""

[commands]
# Основные команды для разработки
type-check = ["npm", "run", "type-check"]
lint = ["npm", "run", "lint"]
build = ["npm", "run", "build"]
test = ["npm", "run", "test"]
dev = ["npm", "run", "dev"]

# Форматирование и проверки
format = ["npm", "run", "format"]
preview = ["npm", "run", "preview"]

# Установка зависимостей (с флагом для совместимости)
install = ["npm", "install", "--legacy-peer-deps"]
install-clean = ["npm", "ci", "--legacy-peer-deps"]

# Git операции
git-status = ["git", "status", "--porcelain"]
git-log = ["git", "log", "--oneline", "-10"]

[commands.deploy]
command = ["npm", "run", "deploy"]
doc = "Деплой на GitHub Pages через GitHub Actions"

[commands.analyze]
command = ["npm", "run", "analyze"]
doc = "Анализ размера бандла и производительности"
